/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

main(){
	int i=1, j=2, aux=1, even=0,  count=1;
	do{
		if(i==1){
		aux=i;
		i=i+j;
		count=count+2;
	}
	else{
		aux=i;
		i=i+j;
		j=aux;
			count++;
	}
	if(i%2==0){
		even=even+i;
	}

	}
	while(i<4000000);
	printf("Soma:%d",even+2);
}


